# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapGenerator(object):
    def setupUi(self, MapGenerator):
        MapGenerator.setObjectName("MapGenerator")
        MapGenerator.resize(1015, 698)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MapGenerator.setFont(font)
        MapGenerator.setStyleSheet("background-color: rgb(130, 130, 130);\n"
"color: rgb(255, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(MapGenerator)
        self.centralwidget.setObjectName("centralwidget")
        self.map_widget = QtWidgets.QLabel(self.centralwidget)
        self.map_widget.setGeometry(QtCore.QRect(40, 30, 931, 501))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.map_widget.setFont(font)
        self.map_widget.setText("")
        self.map_widget.setObjectName("map_widget")
        self.x_line = QtWidgets.QLineEdit(self.centralwidget)
        self.x_line.setGeometry(QtCore.QRect(190, 550, 501, 31))
        self.x_line.setObjectName("x_line")
        self.y_line = QtWidgets.QLineEdit(self.centralwidget)
        self.y_line.setGeometry(QtCore.QRect(190, 590, 501, 31))
        self.y_line.setObjectName("y_line")
        self.size_line = QtWidgets.QLineEdit(self.centralwidget)
        self.size_line.setGeometry(QtCore.QRect(190, 630, 501, 31))
        self.size_line.setObjectName("size_line")
        self.x_label = QtWidgets.QLabel(self.centralwidget)
        self.x_label.setGeometry(QtCore.QRect(30, 555, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setGeometry(QtCore.QRect(30, 590, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(30, 630, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.size_label.setFont(font)
        self.size_label.setObjectName("size_label")
        self.show_map = QtWidgets.QPushButton(self.centralwidget)
        self.show_map.setGeometry(QtCore.QRect(730, 560, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.show_map.setFont(font)
        self.show_map.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(130, 130, 130);")
        self.show_map.setObjectName("show_map")
        MapGenerator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MapGenerator)
        self.statusbar.setObjectName("statusbar")
        MapGenerator.setStatusBar(self.statusbar)

        self.retranslateUi(MapGenerator)
        QtCore.QMetaObject.connectSlotsByName(MapGenerator)

    def retranslateUi(self, MapGenerator):
        _translate = QtCore.QCoreApplication.translate
        MapGenerator.setWindowTitle(_translate("MapGenerator", "Генератор карты"))
        self.x_label.setText(_translate("MapGenerator", "Координата по x"))
        self.y_label.setText(_translate("MapGenerator", "Координата по y"))
        self.size_label.setText(_translate("MapGenerator", "<html><head/><body><p>Масштаб</p></body></html>"))
        self.show_map.setText(_translate("MapGenerator", "Показать карту"))
